{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.31-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.31-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.31-1.20.jar",
          "size": 1340307,
          "sha512": "b7e9c4ebec558de953c7088370f34984fe930d185e95227d4b1a1260169e114ccc61e3904ea288ee924e5a35dee1e52376b96a7e2798245f2a579272ffeb344b",
          "sha256": "f2a05a0d3a6735024abe0dc92a8badafc45c1cd0e0e28c44e1d3e74b81c5801c",
          "sha1": "225aab25f6a384fad4201bc0e6e89ee036bce2a2",
          "md5": "a173eeced90caaf6ff16185264b75b4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.31-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.31-1.20.jar",
          "size": 1340307,
          "sha512": "b7e9c4ebec558de953c7088370f34984fe930d185e95227d4b1a1260169e114ccc61e3904ea288ee924e5a35dee1e52376b96a7e2798245f2a579272ffeb344b",
          "sha256": "f2a05a0d3a6735024abe0dc92a8badafc45c1cd0e0e28c44e1d3e74b81c5801c",
          "sha1": "225aab25f6a384fad4201bc0e6e89ee036bce2a2",
          "md5": "a173eeced90caaf6ff16185264b75b4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.31-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.31-1.20-sources.jar",
          "size": 143624,
          "sha512": "8280e629dffac9f3c6c6b29b3c6bab2d71c5c2a04f4b949a9bdf829300b76724b5b86e2207e52697f725da09d73af3e76614e71a32d795e6cc0586efe6f69ae3",
          "sha256": "4da4d8bf9da347533b763efa522700623fc3026a887116c8cf889dbeda484d60",
          "sha1": "32c86506492d981152b2d480d4df47de0ae93553",
          "md5": "2e053e95ec064ad61f474cebe9dd4d6d"
        }
      ]
    }
  ]
}
