{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.44-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.44-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.44-1.20.jar",
          "size": 1351784,
          "sha512": "3013d89b9310ea6ea49f63895c88954641410718d24f1474146b7602efa801a14cd04c075caef770f63ebcdfbb907150e035ad4c775bc10f2c9b50228bf0ade6",
          "sha256": "e6bcc194a7e4eb5e8445120133bfdbb36429352ff18c83f274702374737c1897",
          "sha1": "54bd3085cd35899ac22468aa87b2494190dda449",
          "md5": "ba62961c5337d0722fc8212c3a70e21f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.44-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.44-1.20.jar",
          "size": 1351784,
          "sha512": "3013d89b9310ea6ea49f63895c88954641410718d24f1474146b7602efa801a14cd04c075caef770f63ebcdfbb907150e035ad4c775bc10f2c9b50228bf0ade6",
          "sha256": "e6bcc194a7e4eb5e8445120133bfdbb36429352ff18c83f274702374737c1897",
          "sha1": "54bd3085cd35899ac22468aa87b2494190dda449",
          "md5": "ba62961c5337d0722fc8212c3a70e21f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.44-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.44-1.20-sources.jar",
          "size": 146756,
          "sha512": "bfb29bfe68e0ae08e38120beb52218a943136555b82eb2ef27e3205c7e6582642b0465990d2ab666ad79d3bfb00cb6f46137a0e3db15a8187e6d664b729b2a48",
          "sha256": "1a7157a03461c7770d5fee8e83bd3024963a1cbf80d5806662a2898210c3eecc",
          "sha1": "f900cdc4b0beffde9b63083d0de4dc3376317f47",
          "md5": "258b9b1dc9f0a8aa9dd1e22cd595659c"
        }
      ]
    }
  ]
}
