{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.39-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.39-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.39-1.20.jar",
          "size": 1351891,
          "sha512": "e3b5c50e1116ebb5550ae9cc55f24581ff70118ed7d005a6f4cf98e491e096f0c8fbcb16e205f8a41696950d9a199b078f5b88bee3bc3c1901253e5abbd9ca86",
          "sha256": "75e6828255a902398098d40c8bf9027d8ceb85f7b60cafef5a04a80bc936439f",
          "sha1": "9a68f8913e947af0f1b7ae0e28e99889052c37aa",
          "md5": "e7825e14c5514673c04116b13eff1376"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.39-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.39-1.20.jar",
          "size": 1351891,
          "sha512": "e3b5c50e1116ebb5550ae9cc55f24581ff70118ed7d005a6f4cf98e491e096f0c8fbcb16e205f8a41696950d9a199b078f5b88bee3bc3c1901253e5abbd9ca86",
          "sha256": "75e6828255a902398098d40c8bf9027d8ceb85f7b60cafef5a04a80bc936439f",
          "sha1": "9a68f8913e947af0f1b7ae0e28e99889052c37aa",
          "md5": "e7825e14c5514673c04116b13eff1376"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.39-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.39-1.20-sources.jar",
          "size": 149845,
          "sha512": "3c409c755e760d3dd64b2b3a5d36ceea0e561725ba9ad53c701fcb5a877f173102dc0ab4c24ebb3952f7d438173e30a35abfa421de5663aa98ad3e83de4e4678",
          "sha256": "3dad315fa39586a34f5f228a21f219617284ecbe2ae41202723567909022b5ec",
          "sha1": "d2f220107d23bb4539e017a047cfe090893daf7a",
          "md5": "93ef2819c26e91ce8cd5c966c2066710"
        }
      ]
    }
  ]
}
