{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.1-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.1-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.1-1.20.jar",
          "size": 1351687,
          "sha512": "cfb1e9de89bfd414ecfeed72736c0d2b560fcbbc3cc35d09325791f4522f69c92c2b043e8cf08d0943b3a469423193bf48cf2c6f780822412cffa340c7661570",
          "sha256": "9a3ac5e957a6e5692bbadb4840732af3ffceab721e97ed3b6cfaaec4f7efa90c",
          "sha1": "beeb09af8dec9a11955e118af3105123600f84d8",
          "md5": "8bba73a93a8f999cb7779e03bdd39d1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.1-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.1-1.20.jar",
          "size": 1351687,
          "sha512": "cfb1e9de89bfd414ecfeed72736c0d2b560fcbbc3cc35d09325791f4522f69c92c2b043e8cf08d0943b3a469423193bf48cf2c6f780822412cffa340c7661570",
          "sha256": "9a3ac5e957a6e5692bbadb4840732af3ffceab721e97ed3b6cfaaec4f7efa90c",
          "sha1": "beeb09af8dec9a11955e118af3105123600f84d8",
          "md5": "8bba73a93a8f999cb7779e03bdd39d1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.1-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.1-1.20-sources.jar",
          "size": 146770,
          "sha512": "2fee50ccd499758fd6ef670f571043604d1663947ac62cf641cfb92bec489e47afbdcf634f8f6a37c61c07215a4ab861a4a1226b3b6c5bc775aae5e9962da103",
          "sha256": "844479c6f5c15d9a91fd81bba2f64fdecf635ee279b209ce16666c6611daa0f9",
          "sha1": "244b8df3bfdfa116a0e0c9138520afbe4819fbee",
          "md5": "0f6ac221c0ede74e342d35cdb2d7ebaa"
        }
      ]
    }
  ]
}
