{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.3-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.3-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.3-1.20.jar",
          "size": 1352295,
          "sha512": "1175083113300ea0bf907244cf61349466a349d1fd427c919c48f067915cad28ceff6cdb630503c3ea9cebdf79c1c5a06aef0cdd3dcb2f8e898389a7d354e51f",
          "sha256": "15222206289304b67eafd77f418f69521bc182b3ab722ec19e69584bcb0e6d28",
          "sha1": "b9916b2eb96a291f0b251c9556952d63f6ef50b3",
          "md5": "dfd1812cd8e6ac4b3fddb37fcf2a4892"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.3-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.3-1.20.jar",
          "size": 1352295,
          "sha512": "1175083113300ea0bf907244cf61349466a349d1fd427c919c48f067915cad28ceff6cdb630503c3ea9cebdf79c1c5a06aef0cdd3dcb2f8e898389a7d354e51f",
          "sha256": "15222206289304b67eafd77f418f69521bc182b3ab722ec19e69584bcb0e6d28",
          "sha1": "b9916b2eb96a291f0b251c9556952d63f6ef50b3",
          "md5": "dfd1812cd8e6ac4b3fddb37fcf2a4892"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.3-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.3-1.20-sources.jar",
          "size": 147030,
          "sha512": "7b909ea3775771ae863e2ae8449819c2e3e9971c99867ed46ec34afc866e56b01533bee15c0b0d10a2063883b42a943d2449772b61a0cbcc5e56bd6e047423dd",
          "sha256": "fdec18180f1078b2a071428983ba745670a7438f081c991b56f4429990458f0f",
          "sha1": "133297d52304d7d8b2885becbbe128106e5c0534",
          "md5": "34dfdff4249e7075fa7ecfe10436fb21"
        }
      ]
    }
  ]
}
