{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.10-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.10-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.10-1.20.jar",
          "size": 1351696,
          "sha512": "e4840a3921540dac3c3c2aedc179679c54492d0b8e40ce8160ddb825d97b29bd7b62290ed2e4549bfec6e378c97431a4a56928a871e62d26a2165c435ed1a4b8",
          "sha256": "911c4657aaa04550e1a4352c8e7ce913685a96aa31ed8042c3a4d1f2b55a3b90",
          "sha1": "abcf477055e74dedc6267888635349822d27e5c1",
          "md5": "13a05b9bdf3528eafd373459358d3754"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.10-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.10-1.20.jar",
          "size": 1351696,
          "sha512": "e4840a3921540dac3c3c2aedc179679c54492d0b8e40ce8160ddb825d97b29bd7b62290ed2e4549bfec6e378c97431a4a56928a871e62d26a2165c435ed1a4b8",
          "sha256": "911c4657aaa04550e1a4352c8e7ce913685a96aa31ed8042c3a4d1f2b55a3b90",
          "sha1": "abcf477055e74dedc6267888635349822d27e5c1",
          "md5": "13a05b9bdf3528eafd373459358d3754"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.10-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.10-1.20-sources.jar",
          "size": 146625,
          "sha512": "af15fe82627a27e3283354fb5a92b7135f02b16063c41ad62dd07565631a3fb85411c3fac87befc0d465faebae8f265abab7b9371a93a20ac230155fcff26454",
          "sha256": "9fc08da3277146d1ea78993f9b05daa4971b441b87923786f99b6c67b7c49113",
          "sha1": "8f22eaebfc06008821b343a5ca4abd489ec6fe1b",
          "md5": "fbfd18e458aecbc801189c299f18a30f"
        }
      ]
    }
  ]
}
