{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.29-1.20-pre7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.29-1.20-pre7.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.29-1.20-pre7.jar",
          "size": 1347609,
          "sha512": "e608a205f602faaa45c82f801d7758030777aa2017b20086ca7fac1746e88759d6cc0265fe9ec133a563409627daeda03181ae2ba46684c603483176af22b4d3",
          "sha256": "5a9c3cce8d8d305160371e846915c57044058d47b1d400644ce2f5da170d3439",
          "sha1": "81789d880b6b8a9e3dfe17a73279a95f1efe1e83",
          "md5": "ef1f2d2997c1170d82df755db3fb80ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.82.1+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.29-1.20-pre7.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.29-1.20-pre7.jar",
          "size": 1347609,
          "sha512": "e608a205f602faaa45c82f801d7758030777aa2017b20086ca7fac1746e88759d6cc0265fe9ec133a563409627daeda03181ae2ba46684c603483176af22b4d3",
          "sha256": "5a9c3cce8d8d305160371e846915c57044058d47b1d400644ce2f5da170d3439",
          "sha1": "81789d880b6b8a9e3dfe17a73279a95f1efe1e83",
          "md5": "ef1f2d2997c1170d82df755db3fb80ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.29-1.20-pre7-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.29-1.20-pre7-sources.jar",
          "size": 146692,
          "sha512": "826f943e92b1f9c0f51256a4cd954ed2c783ab6b4d596bd9dce2d53eb133f7746dae253166b51fbabaf2aca15ce2246d2b4b18d55ffc5227893aa834277757ce",
          "sha256": "fa070bfdcd9f1f95629d8db1e1636180fcd836a8732e8eea4c3bd602a473f43c",
          "sha1": "39a8c05babcf48a30558d45f508ae90afe9021f0",
          "md5": "62add97ce86fec401b961a922af1e5aa"
        }
      ]
    }
  ]
}
