{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.33-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.33-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.33-1.20.jar",
          "size": 1345203,
          "sha512": "c9918e7ab8e70f539975f326bf2415ac29bbc1588e471688cadbb4ce128cfd42f76bfcd071fdbca53eac53c111694c9be27c876c3e9871f58537591d5418e3cc",
          "sha256": "ab1e6157a87e50cb35c57e70820725eb3c38194abc170b48fec45999867af14f",
          "sha1": "76104c3150a3bf7ffb398c624c0b3f1616ba6e03",
          "md5": "7b7a02c26914802b4c4b10d77d9908cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.33-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.33-1.20.jar",
          "size": 1345203,
          "sha512": "c9918e7ab8e70f539975f326bf2415ac29bbc1588e471688cadbb4ce128cfd42f76bfcd071fdbca53eac53c111694c9be27c876c3e9871f58537591d5418e3cc",
          "sha256": "ab1e6157a87e50cb35c57e70820725eb3c38194abc170b48fec45999867af14f",
          "sha1": "76104c3150a3bf7ffb398c624c0b3f1616ba6e03",
          "md5": "7b7a02c26914802b4c4b10d77d9908cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.33-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.33-1.20-sources.jar",
          "size": 145949,
          "sha512": "cc6348b90231f916410a2962290768e636df8f93c0b6e54001fe46ddc26ae36b83aa3036cc43e863cc0498978ab849cbe8019570abdbf96eb1c0edee5a1291d3",
          "sha256": "8db823052dfeb550cfee8cdeeee4d7f54351428a12f73b376655c42dac5e12b7",
          "sha1": "5a5e2c121af31f1e831b627a0a7cace71130aa8d",
          "md5": "fd27eefd71c31ef671ad16d954bad028"
        }
      ]
    }
  ]
}
