{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.37-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.37-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.37-1.20.jar",
          "size": 1346612,
          "sha512": "8b8f41228c0252cf229a5e858cc2e7d0169c0bca67eb794394ae9ebcb42370440530927f3ff2b6576b3de8f1b7e852cadfa89bb9ca67f76fe7de014d78ada119",
          "sha256": "5d19596581bfc1d2f14e5594d8a2caee90629fd7924dbaed6c96a1439208e132",
          "sha1": "e5fdcd7bbd183ff57bf3843ce2188f95bcfda6ca",
          "md5": "3d81d02c2df19d6dc56a5201d8b3576d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.37-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.37-1.20.jar",
          "size": 1346612,
          "sha512": "8b8f41228c0252cf229a5e858cc2e7d0169c0bca67eb794394ae9ebcb42370440530927f3ff2b6576b3de8f1b7e852cadfa89bb9ca67f76fe7de014d78ada119",
          "sha256": "5d19596581bfc1d2f14e5594d8a2caee90629fd7924dbaed6c96a1439208e132",
          "sha1": "e5fdcd7bbd183ff57bf3843ce2188f95bcfda6ca",
          "md5": "3d81d02c2df19d6dc56a5201d8b3576d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.37-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.37-1.20-sources.jar",
          "size": 146579,
          "sha512": "a530b9a15f1645c00a846514589beaf858838f15bf951ec729752392317b688cd64bc756e92557be90cbf659f9926f5aaa1c9e3b040f1102fad3633db1cd9189",
          "sha256": "833651e7200af6f04eaea3f1f2d3c27289cbc68d337699996ad47e12b7af3890",
          "sha1": "d7eb99a255195751726212dd94c5b34013e5b013",
          "md5": "01c40cce30d37c58ed35aff36a346b9d"
        }
      ]
    }
  ]
}
