{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.9-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.9-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.9-1.20.jar",
          "size": 1351514,
          "sha512": "f0b3ba97ef5bef083bf85bc763bbb647dca7182b4e9aeb76fe751d1119a9b5053e2a0a8be3cf3c9bcbdfca82892a2eed4feea827126ccf03861198cc999c088a",
          "sha256": "6f9dc450cdf9b207d7fe99a73ed718d37c8e3980c1c8c02ffbc3acbc506a1cff",
          "sha1": "e4a5f0809d4731f7429f7357bf80935cfe2074d9",
          "md5": "622e29b54aea6a41a043cc3d04f15388"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.9-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.9-1.20.jar",
          "size": 1351514,
          "sha512": "f0b3ba97ef5bef083bf85bc763bbb647dca7182b4e9aeb76fe751d1119a9b5053e2a0a8be3cf3c9bcbdfca82892a2eed4feea827126ccf03861198cc999c088a",
          "sha256": "6f9dc450cdf9b207d7fe99a73ed718d37c8e3980c1c8c02ffbc3acbc506a1cff",
          "sha1": "e4a5f0809d4731f7429f7357bf80935cfe2074d9",
          "md5": "622e29b54aea6a41a043cc3d04f15388"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.9-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.9-1.20-sources.jar",
          "size": 146602,
          "sha512": "fa3fedfa2f16ca011aa4fbd664cbdbec125b4adf25dfb30d6b72dbc34d88e98b3eb93869d952d45db4834007136618a209468f71bb1df57d3d8afeeb2f603823",
          "sha256": "e18919fd8cd3148e427a8e2cf8d479093e325f9fd1d5228aaf1c849ad0e4c737",
          "sha1": "7e2af468e635760a92039994a52cdabaddc91fe2",
          "md5": "32575ec41fa27d6331bc7046122b4f3c"
        }
      ]
    }
  ]
}
