{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.8-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.8-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.8-1.20.jar",
          "size": 1352999,
          "sha512": "8c90326dc52cea4f12d27a33e39e9d01c9e75539679d2739aa945beb241633c83932e90bc7e22a5cba2bf2edef328cf1b0a5f3e665284b673f42194c96be943c",
          "sha256": "5f89d34aaa6e601bebff273c658362121d368be4b5e9bdbb585443925366ebdd",
          "sha1": "2393ace997e60f51013d25cba9e7c9a4a654540a",
          "md5": "83d4f98490b342fa59e734fc6d719a95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.8-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.8-1.20.jar",
          "size": 1352999,
          "sha512": "8c90326dc52cea4f12d27a33e39e9d01c9e75539679d2739aa945beb241633c83932e90bc7e22a5cba2bf2edef328cf1b0a5f3e665284b673f42194c96be943c",
          "sha256": "5f89d34aaa6e601bebff273c658362121d368be4b5e9bdbb585443925366ebdd",
          "sha1": "2393ace997e60f51013d25cba9e7c9a4a654540a",
          "md5": "83d4f98490b342fa59e734fc6d719a95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.8-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.8-1.20-sources.jar",
          "size": 147398,
          "sha512": "88325f88c1fd359f4acb0b72649477acfdfb9962c83d4fc0440149dab792cd9d638f4f12b76f8d71b755fbdc8b26c333862d0d8b99cb48779d3a8dd0d4e0e4f7",
          "sha256": "d04a93607c79affe5bfa1bd938bba5bd70f4883649735e83f38a0e66706c1896",
          "sha1": "85d7f3938864ba8dc2cd833b77baecb0be54856c",
          "md5": "bfc7a94a2ba48f77b17d4f9dee0615b8"
        }
      ]
    }
  ]
}
