{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.7-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.7-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.7-1.20.jar",
          "size": 1354618,
          "sha512": "c00056704f197bcb9dd63fb2f03481d921c4a2ce0213d5e4f589a777274135f0cbe915c1dc4ac2160304f567a2aaac427e39774326d64918eb6c7dbb140ea619",
          "sha256": "8e7462a20652b835bccea8da538392821710ecf8445157d060daa231f0b5c976",
          "sha1": "4383863d250db7589becc07ae80c3e0c8fcc60cb",
          "md5": "15da3d0c7e4e78ee512344e334980eee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.7-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.7-1.20.jar",
          "size": 1354618,
          "sha512": "c00056704f197bcb9dd63fb2f03481d921c4a2ce0213d5e4f589a777274135f0cbe915c1dc4ac2160304f567a2aaac427e39774326d64918eb6c7dbb140ea619",
          "sha256": "8e7462a20652b835bccea8da538392821710ecf8445157d060daa231f0b5c976",
          "sha1": "4383863d250db7589becc07ae80c3e0c8fcc60cb",
          "md5": "15da3d0c7e4e78ee512344e334980eee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.7-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.7-1.20-sources.jar",
          "size": 147150,
          "sha512": "75676ecb74c8a65bffad6ba131d8cd4f75457f6d701d1947228cf4f04f432ae744bfc30557a61d973f167b6d25db4d63eaa8d2a0a440a4f01051e33452c18a34",
          "sha256": "4d3ba233159747243dbb99492fa278589b768f80daf8ac2125495284270495fc",
          "sha1": "2723097a19170fd0961dc3c2d2238d3a7facb311",
          "md5": "c04e0d9c25209a4dd74cd298019eeb3f"
        }
      ]
    }
  ]
}
