{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-normandy-login-fabric",
    "version": "1.0.0.0-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.0-1.20.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.0-1.20.jar",
          "size": 156138,
          "sha512": "80858e04d49aeb91b271ba5eed884477325cae9230ffa6f7017281171516b38581a4ff34edb8977d28c488d29e9b29d6353ba1510c086acfa8d4c0a6c9b730ae",
          "sha256": "66ab9eebc373485841fef4f353b72268cb0abc31a3a8815fddb8f4731e27c13b",
          "sha1": "97f86c344dcc135cd10e1de8c348211e378f7f7f",
          "md5": "a43a7813f918a45217c79dc8a4a71594"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "io.github.xenfork",
          "module": "nucleoplasm-api-fabric",
          "version": {
            "requires": "1.0.1.5-1.20"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.0-1.20.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.0-1.20.jar",
          "size": 156138,
          "sha512": "80858e04d49aeb91b271ba5eed884477325cae9230ffa6f7017281171516b38581a4ff34edb8977d28c488d29e9b29d6353ba1510c086acfa8d4c0a6c9b730ae",
          "sha256": "66ab9eebc373485841fef4f353b72268cb0abc31a3a8815fddb8f4731e27c13b",
          "sha1": "97f86c344dcc135cd10e1de8c348211e378f7f7f",
          "md5": "a43a7813f918a45217c79dc8a4a71594"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.0-1.20-sources.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.0-1.20-sources.jar",
          "size": 146625,
          "sha512": "b2b1b8245403dab26dcb4145fb770e3912c324fe6ee4acae33b74a5399e1cc9c182c133594f03501a130658cbe80b71eac62997133cd0ca431a6e233f91a2832",
          "sha256": "a57c8881848d9064c4042660954f023eb2d253e80fb329e0dc59d5470957843d",
          "sha1": "3e4a3dcb941e2f6f39bf5bc7d24688a800c76e47",
          "md5": "b20a1cb4aec16984a0594bdb5a0c04c6"
        }
      ]
    }
  ]
}
