{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-normandy-login-fabric",
    "version": "1.0.0.2-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1.jar",
          "size": 156185,
          "sha512": "f4997de7ce4aeaa378342c8483ff30aa6b64b7ea3810c7e837ac122c2bdc5232f9a9d636cbf298e7950182d178a689419e6edc489e26aeda3185061ff627519c",
          "sha256": "e4b76ae9870b032fc4ffb31be48472eae58d42b6a92ecfad7f0b48ecd23e7ca9",
          "sha1": "75b59ec8411f9d264c2275d3daa457896eea7dda",
          "md5": "9c1a052ff5d22787ad93e1c51b7c6c77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.84.0+1.20.1"
          }
        },
        {
          "group": "io.github.xenfork",
          "module": "nucleoplasm-api-fabric",
          "version": {
            "requires": "1.0.1.12-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1.jar",
          "size": 156185,
          "sha512": "f4997de7ce4aeaa378342c8483ff30aa6b64b7ea3810c7e837ac122c2bdc5232f9a9d636cbf298e7950182d178a689419e6edc489e26aeda3185061ff627519c",
          "sha256": "e4b76ae9870b032fc4ffb31be48472eae58d42b6a92ecfad7f0b48ecd23e7ca9",
          "sha1": "75b59ec8411f9d264c2275d3daa457896eea7dda",
          "md5": "9c1a052ff5d22787ad93e1c51b7c6c77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1-sources.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1-sources.jar",
          "size": 146308,
          "sha512": "8a37793f4c33f24f8cdbd1f08cc22a4a1928f60e96a961345bc9794cad00f464753ede7c0bf5161b990db8293009e1bad494d92d788f541c094fdcb7dbaef16b",
          "sha256": "f4b0cc4d4714cb598b1087db4ddfcefe0d7ef6249996e28be7a4504f4caecf31",
          "sha1": "b064be3808a8602875a8292188b16335526f8c1b",
          "md5": "be6b05c2fe4e94baceb0d72e8d8c0c31"
        }
      ]
    }
  ]
}
