{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-normandy-login-fabric",
    "version": "1.0.0.2-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1.jar",
          "size": 154506,
          "sha512": "f3f003d21a6dfc7be8bbffcea79f8f58c23170faca2fd81f53227ba30927269eac98b088c673d8cabc3b82c8286b4e7c75e5e08d6d730707f85c1cf4828240f8",
          "sha256": "642934bf1e6cb480c553fa37eb2e3d2d27a06b314696b49c8e48c7a38296e2c8",
          "sha1": "894d517abe915c3c431ff0330650e3ffd31cc2ac",
          "md5": "1fb3154ef6c36b726f790f62e57473d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.84.0+1.20.1"
          }
        },
        {
          "group": "io.github.xenfork",
          "module": "nucleoplasm-api-fabric",
          "version": {
            "requires": "1.0.1.13-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1.jar",
          "size": 154506,
          "sha512": "f3f003d21a6dfc7be8bbffcea79f8f58c23170faca2fd81f53227ba30927269eac98b088c673d8cabc3b82c8286b4e7c75e5e08d6d730707f85c1cf4828240f8",
          "sha256": "642934bf1e6cb480c553fa37eb2e3d2d27a06b314696b49c8e48c7a38296e2c8",
          "sha1": "894d517abe915c3c431ff0330650e3ffd31cc2ac",
          "md5": "1fb3154ef6c36b726f790f62e57473d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1-sources.jar",
          "url": "nucleoplasm-normandy-login-fabric-1.0.0.2-1.20.1-sources.jar",
          "size": 145410,
          "sha512": "aa878c6356405a59b9fe52106ead2ce00a510ff321b6f3f9812a44fa0fe774899e2a7c07b2adfdb6d0878aad671df4a795351b304936da126f4d26aab37514e3",
          "sha256": "35c82b02bffbe7f1d53c0bc534c4227b4466d3ba8cd8aafe168a5073877e1c9c",
          "sha1": "15f83113aa8be27c8a8a6f1de47106bf8d52b636",
          "md5": "507fb74401a5a776e683b809e5a7ede9"
        }
      ]
    }
  ]
}
