{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.36-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.36-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.36-1.20.jar",
          "size": 1345376,
          "sha512": "55e71303e83b77c3dc40311a80c9d6a87d5d4429d2c0bf1ace86f7df22ec3b9a39a3ad461012cdcdf6cf4ee301f32c18a8ce05fdd9e08dd18807e14445489295",
          "sha256": "da380fb605c33029d59752430eb0c94856a47df2c9266bee5c52296bac4946db",
          "sha1": "7e4e5562e3f397ef4a27e9f3f586ef0ae024f3fe",
          "md5": "e7ad2b59292af6b94c56379881c73686"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.36-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.36-1.20.jar",
          "size": 1345376,
          "sha512": "55e71303e83b77c3dc40311a80c9d6a87d5d4429d2c0bf1ace86f7df22ec3b9a39a3ad461012cdcdf6cf4ee301f32c18a8ce05fdd9e08dd18807e14445489295",
          "sha256": "da380fb605c33029d59752430eb0c94856a47df2c9266bee5c52296bac4946db",
          "sha1": "7e4e5562e3f397ef4a27e9f3f586ef0ae024f3fe",
          "md5": "e7ad2b59292af6b94c56379881c73686"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.36-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.36-1.20-sources.jar",
          "size": 146028,
          "sha512": "777998188f272ccfc18b04fee8b94562cf8647b3b15dabc5fa11c470f7f4a80cc8d042f9defe1b4a07c1351098697bb1751e8d356f56d7f60d7185a5a8910c65",
          "sha256": "91a96c8a5e343a6554044c0edcfc77bfa5afc47f91591f36900b1183b5057228",
          "sha1": "353528e71b6653e78f1658163167f7335de8dbdc",
          "md5": "b6b574eaf770bc8f4bd9f5f41fdc8032"
        }
      ]
    }
  ]
}
