{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.38-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.38-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.38-1.20.jar",
          "size": 1351858,
          "sha512": "5cbab66ec85bf1f96bb57423ac518ae2c7540ece7b7f74b9bfbd862fdf6af8e596ceef32d956c6bdf7f14f089d94d0c0cfd350db51849ddb37e19c046fd35cd1",
          "sha256": "f37ce238abb1c67eec4134db11a2a2d2dbc2f888067080d03ac18dcfabdd67f3",
          "sha1": "7933e3ee64d4e88c42ab379b8d9ca859c12d4d74",
          "md5": "884cdb3613e2f2b9e0328c3f38751dc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.38-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.38-1.20.jar",
          "size": 1351858,
          "sha512": "5cbab66ec85bf1f96bb57423ac518ae2c7540ece7b7f74b9bfbd862fdf6af8e596ceef32d956c6bdf7f14f089d94d0c0cfd350db51849ddb37e19c046fd35cd1",
          "sha256": "f37ce238abb1c67eec4134db11a2a2d2dbc2f888067080d03ac18dcfabdd67f3",
          "sha1": "7933e3ee64d4e88c42ab379b8d9ca859c12d4d74",
          "md5": "884cdb3613e2f2b9e0328c3f38751dc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.38-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.38-1.20-sources.jar",
          "size": 149825,
          "sha512": "63fb7beaa44a22d4cffffd8a2f7b5166c0b975f001d14165e354ccd65bb0f2d3be004eeed7196cb51f8b39a93f2aa52c7ec164c90715bae7c6d57c40a2377c9f",
          "sha256": "27d5269ecff14dd97b8236d5d8d983e30803182f3a6af2d08d17edc70f1f5961",
          "sha1": "276dd3ce591d1b8730c14fb0b5a1e95a7aab00d7",
          "md5": "ea6d4b8784e381b0e63e2990f56269af"
        }
      ]
    }
  ]
}
