{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.35-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.35-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.35-1.20.jar",
          "size": 1345254,
          "sha512": "5d7d4800c07a658fc6f5210f30a2529037fead3bd16906e177c9810653fd3bb8feecd4527bf6c6481b6971267cc4ed3d02acfb1c2a8cb1bbb08289e326db2aaa",
          "sha256": "116669b4ff8ffe25e8e254121f67c4e8d33a6669717bd2d1be9fb17029bd52b5",
          "sha1": "ad78d48146ca474736cf6cb04420afbe6d7369a2",
          "md5": "0a4aff128f368527e91fd4f24fe51fa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.35-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.35-1.20.jar",
          "size": 1345254,
          "sha512": "5d7d4800c07a658fc6f5210f30a2529037fead3bd16906e177c9810653fd3bb8feecd4527bf6c6481b6971267cc4ed3d02acfb1c2a8cb1bbb08289e326db2aaa",
          "sha256": "116669b4ff8ffe25e8e254121f67c4e8d33a6669717bd2d1be9fb17029bd52b5",
          "sha1": "ad78d48146ca474736cf6cb04420afbe6d7369a2",
          "md5": "0a4aff128f368527e91fd4f24fe51fa1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.35-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.35-1.20-sources.jar",
          "size": 145966,
          "sha512": "87d8fa68b3dc3330c12b313f2870be538786d8c3f1c2a4bd647295117be339b1bddb30f01b40156f7ffbf10c52325e2515c925e7448f8c5851fb2ccc24d138f0",
          "sha256": "75df52d2e2832d567487907b3db0527ad92d9f1e492241f6ac17f78d10784ac0",
          "sha1": "54474bfc241defc52553a86846cc3937cad8113a",
          "md5": "ac673619e12339e56e4fe4b3b134f08d"
        }
      ]
    }
  ]
}
