{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.32-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.32-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.32-1.20.jar",
          "size": 1345183,
          "sha512": "718b48d23aea0025f1332d95a8761778d19eff027822a5f55900845cb0169aa4fcbae1587122c0d40c6b97d98c933f9559747c10e3211875e7227afcdcea462d",
          "sha256": "b7dba150b8c7745bf3369952c67ad45837f7c9f4faa1311a4885c8e2b69f61fd",
          "sha1": "97d963667c0b3e610c864d74b47e618313666bdf",
          "md5": "6833bce3144aa29b6c33d1f442a556a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.32-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.32-1.20.jar",
          "size": 1345183,
          "sha512": "718b48d23aea0025f1332d95a8761778d19eff027822a5f55900845cb0169aa4fcbae1587122c0d40c6b97d98c933f9559747c10e3211875e7227afcdcea462d",
          "sha256": "b7dba150b8c7745bf3369952c67ad45837f7c9f4faa1311a4885c8e2b69f61fd",
          "sha1": "97d963667c0b3e610c864d74b47e618313666bdf",
          "md5": "6833bce3144aa29b6c33d1f442a556a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.32-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.32-1.20-sources.jar",
          "size": 145936,
          "sha512": "eb719cd9097e2ea40d874fe25bee450ab1398d094a404a1ec370bdfbfae80957bf72285399aba93e0db3a71564cc928f5b3528e0a990041399820fdd5a7880c6",
          "sha256": "a273d98b85932735c676951459f7cee98e68d8880bac0d26b9bf2f726f9445a7",
          "sha1": "14992ddcb1c648c8ed12b24f99970eafb56624e4",
          "md5": "54af1834d7258b3e579b56728c880372"
        }
      ]
    }
  ]
}
