{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.34-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.34-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.34-1.20.jar",
          "size": 1345259,
          "sha512": "8146eb6464a8c126d51719122a332b8f213c3f296756612094c7f9bef07b3698a90fcb12ad9f14ad98dcbf1ed0ed29b763f7c9ea73cff6f1379f1b0c838f85e0",
          "sha256": "163d09a94ba2837c3062cc798a00349f46e0971528ea7bc476d2ba9f8bcb6e06",
          "sha1": "fe197f155ec37fcc0f5ff503905429b660aa7c2e",
          "md5": "eb6cba3e1e1b1a5052197e273aca650c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.34-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.34-1.20.jar",
          "size": 1345259,
          "sha512": "8146eb6464a8c126d51719122a332b8f213c3f296756612094c7f9bef07b3698a90fcb12ad9f14ad98dcbf1ed0ed29b763f7c9ea73cff6f1379f1b0c838f85e0",
          "sha256": "163d09a94ba2837c3062cc798a00349f46e0971528ea7bc476d2ba9f8bcb6e06",
          "sha1": "fe197f155ec37fcc0f5ff503905429b660aa7c2e",
          "md5": "eb6cba3e1e1b1a5052197e273aca650c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.34-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.34-1.20-sources.jar",
          "size": 145968,
          "sha512": "547d0c1645a9358def2e9df7fec2eed07b9de09e402ae375887a1ac624c8c0f13ac7f7e18688338f8ab068b14dc16c7e2884fa773ac7a2708f16992b336ef52d",
          "sha256": "39e1cd0d0dba6a8f950c9504060ba53ec218aff303abc14df9afb99eebf32d6e",
          "sha1": "a17f9cb8e7290cfd297fe00c2bb4d3aedd95ea00",
          "md5": "8714e300107d43ed716f0609ba039e8e"
        }
      ]
    }
  ]
}
