{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.40-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.40-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.40-1.20.jar",
          "size": 1358612,
          "sha512": "8f01f5bf3f7d364ab9e0b8eebd2060722642823ab6f0a729fc1dce656614a6977efbff90a5ac1c799fd1937ee7318e12e6e0abec09d78a6d06a87ae69157978e",
          "sha256": "574114b560dff737230187b12c3d51341d4e11221d41f007191f925f5495ae1b",
          "sha1": "cfa479440ed522eb002764886e2a8f16b992d700",
          "md5": "9c819fdae9b6ba48553bdbb48eea60be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.40-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.40-1.20.jar",
          "size": 1358612,
          "sha512": "8f01f5bf3f7d364ab9e0b8eebd2060722642823ab6f0a729fc1dce656614a6977efbff90a5ac1c799fd1937ee7318e12e6e0abec09d78a6d06a87ae69157978e",
          "sha256": "574114b560dff737230187b12c3d51341d4e11221d41f007191f925f5495ae1b",
          "sha1": "cfa479440ed522eb002764886e2a8f16b992d700",
          "md5": "9c819fdae9b6ba48553bdbb48eea60be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.40-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.40-1.20-sources.jar",
          "size": 151611,
          "sha512": "94baf1194c39ad9d87e49cae70a9ff684aa629c258fb5b4218e8563a555ce541f9a349235d83d28f1f4019ab243d4ba0d7ce57db3277d763c3952e6a690c11d0",
          "sha256": "187361c6115fa8ae7f39f612b2f82d6414c361238b83ab0310a84b37720668e7",
          "sha1": "a4335dfc671f0b2166017e248c0f34bcc67c42f8",
          "md5": "8650d9b78bfbb6aca8d23c18c9a7fb43"
        }
      ]
    }
  ]
}
