{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.18-23w16a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "size": 986823,
          "sha512": "4fae24800862d6d7969664da24f3dadf4f3ff55b62e7aa44472d2a5cece10669988cb48450eca69626664812a73693c5510368ed2bb7c1b3b4db7be602a64560",
          "sha256": "b2836b3d0b9001c6a82b43c64f3e8338454b1534b970cab62236be2aadf4f50e",
          "sha1": "d56766dec6c084b4f61f640c14d97c50f03a68e9",
          "md5": "5cfb1361365980e7d505f9f585e3d7c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.1+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "size": 986823,
          "sha512": "4fae24800862d6d7969664da24f3dadf4f3ff55b62e7aa44472d2a5cece10669988cb48450eca69626664812a73693c5510368ed2bb7c1b3b4db7be602a64560",
          "sha256": "b2836b3d0b9001c6a82b43c64f3e8338454b1534b970cab62236be2aadf4f50e",
          "sha1": "d56766dec6c084b4f61f640c14d97c50f03a68e9",
          "md5": "5cfb1361365980e7d505f9f585e3d7c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a-sources.jar",
          "size": 143549,
          "sha512": "bde0df4a290de3d81b746cd6d33ce941f811718c08c7c66236139347d0b323d509da9444256fbcb6b12f30547fd1190878d2c04b46f953c335e6545d1e181061",
          "sha256": "98b35d5f0e51f0d95fa13ad6d89ccaf0eaf53faf16080be12ceb5543e33e1980",
          "sha1": "d47814ac6b6a29f550739984b6908f7304f40937",
          "md5": "dbe912dfa236ed0dedc1d235fbe1e65d"
        }
      ]
    }
  ]
}
