{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.18-23w16a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "size": 986826,
          "sha512": "2a06addd75a12c7deab782db77ed0bd772da22e7545f6aff4178652b3be68e6b9f7863190b5e084b38719c3fb234c6159a05463e9aa9d71e39bcc1ab2d29fe71",
          "sha256": "d05f240380d41f9a0f0275ded56434472b14c1f237525391a913a5715a8872ce",
          "sha1": "0018d3045678f520aba66ff9d543378c609a7da3",
          "md5": "18204681968a27cca9449592bacedc2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.1+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "size": 986826,
          "sha512": "2a06addd75a12c7deab782db77ed0bd772da22e7545f6aff4178652b3be68e6b9f7863190b5e084b38719c3fb234c6159a05463e9aa9d71e39bcc1ab2d29fe71",
          "sha256": "d05f240380d41f9a0f0275ded56434472b14c1f237525391a913a5715a8872ce",
          "sha1": "0018d3045678f520aba66ff9d543378c609a7da3",
          "md5": "18204681968a27cca9449592bacedc2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a-sources.jar",
          "size": 143517,
          "sha512": "0b3fb62b3400d762ff1568ba1fbc2db33166e264e072e38f90b63218cb71d331bf30d6eda01b31350eec0b4c325550a15464f14f039335a1a56177ef370e8aca",
          "sha256": "f83c5c7288e89615694a00f4c0f59be95dd4be05b8c7ffe82eae1df8a54b2496",
          "sha1": "d070fb5899177131366c7893d8aa137953b01564",
          "md5": "8dbaff5558af55a31eccc994207aac8b"
        }
      ]
    }
  ]
}
