{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.18-23w16a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "size": 983850,
          "sha512": "75450f94ead5524727a8c1a7e407beb56df2e6392a0cb5b1a6de13a32a37ae920c3bff13c667628e22e10e91e007e9aaab12714e2baf95e0dafc4e871ccd4128",
          "sha256": "5debb28292e0daf631e49ded30dad9a253bcf6356478c71fb9dfd7c420007cbf",
          "sha1": "cc03f1359909941b037db1ac11a3871b7d1d6713",
          "md5": "b30f554381843763d7b38707d5bb78b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.1+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a.jar",
          "size": 983850,
          "sha512": "75450f94ead5524727a8c1a7e407beb56df2e6392a0cb5b1a6de13a32a37ae920c3bff13c667628e22e10e91e007e9aaab12714e2baf95e0dafc4e871ccd4128",
          "sha256": "5debb28292e0daf631e49ded30dad9a253bcf6356478c71fb9dfd7c420007cbf",
          "sha1": "cc03f1359909941b037db1ac11a3871b7d1d6713",
          "md5": "b30f554381843763d7b38707d5bb78b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.18-23w16a-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.18-23w16a-sources.jar",
          "size": 142280,
          "sha512": "52dcdf5d787fb9765c77dc68cd09ea0fcae26cd106c9c59dacd788806a4373cfa957a5cfeea0397faa6787784b0386ac1966559f79407f1466601919a72136ec",
          "sha256": "5cc95c5e6a11481d8c8a3fcb4a604dd715dd55d2c042b4f9c446afc1df134836",
          "sha1": "3aea370a8b713ea2ffb6fd3d9eb2797e4f0c5a1f",
          "md5": "e3e06088dded07485926a07329fbeeb9"
        }
      ]
    }
  ]
}
