{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.43-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.43-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.43-1.20.jar",
          "size": 1361713,
          "sha512": "978404dc42da06fd98c59e091e49058226957d975b8e5eeb0c4fc5a39d2d518bbd62e33201ffa3a52163b83e4a73433fb1c22867b9ede191d15fd9332e3cbc6a",
          "sha256": "0b301aa7ed5bb045ef300027423ea0ef8ac8f96811c3246c71d7bd683cca6e9f",
          "sha1": "26462ec9d2df8319f5cee2d3eb6ac1f85095b727",
          "md5": "3e8d13a6cc0797d50f5e327f06047763"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.43-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.43-1.20.jar",
          "size": 1361713,
          "sha512": "978404dc42da06fd98c59e091e49058226957d975b8e5eeb0c4fc5a39d2d518bbd62e33201ffa3a52163b83e4a73433fb1c22867b9ede191d15fd9332e3cbc6a",
          "sha256": "0b301aa7ed5bb045ef300027423ea0ef8ac8f96811c3246c71d7bd683cca6e9f",
          "sha1": "26462ec9d2df8319f5cee2d3eb6ac1f85095b727",
          "md5": "3e8d13a6cc0797d50f5e327f06047763"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.43-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.43-1.20-sources.jar",
          "size": 152526,
          "sha512": "f5738decd6a677473f9dc166acaf694ca81f229e8c84441a3b4f3f9e22c60c87c95ae45e9526c3036f0c35e87146ba85370458a90bb05f89e2b875a9660abedb",
          "sha256": "bbf7ae7f443a27d20ea826836ed5729b7e762c37392c7759bf8953b29b8d3614",
          "sha1": "c657be2ebbbc8aa48938d4326b144a83f4277dca",
          "md5": "7a0f3c38161eaca27bbe5b4546fb7bb7"
        }
      ]
    }
  ]
}
