{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.2-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.2-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.2-1.20.jar",
          "size": 1352101,
          "sha512": "a58294e90174848fc2353285bd715fa4d5eebe3344a8c861003f23b53abc5ca4946b493a31e09334a14c2d529ac83097435d8fd38826fed766f7e91754eae862",
          "sha256": "8818c427423ea69c53160696d0d3fba3cd3ba903f779393ed8bfc2b23dd6aa94",
          "sha1": "66584a58c97156ce6ddb1ce21791b51cd7d859c8",
          "md5": "7f1228b915a489d08ca7f9a8780ea722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.2-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.2-1.20.jar",
          "size": 1352101,
          "sha512": "a58294e90174848fc2353285bd715fa4d5eebe3344a8c861003f23b53abc5ca4946b493a31e09334a14c2d529ac83097435d8fd38826fed766f7e91754eae862",
          "sha256": "8818c427423ea69c53160696d0d3fba3cd3ba903f779393ed8bfc2b23dd6aa94",
          "sha1": "66584a58c97156ce6ddb1ce21791b51cd7d859c8",
          "md5": "7f1228b915a489d08ca7f9a8780ea722"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.2-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.2-1.20-sources.jar",
          "size": 146955,
          "sha512": "27fe2648799d470533e44ddd453daf773ee94d4320555b7fad4dcf9c2456948c6c036bffefa562df4819746ab944ce1e462a0995e073552d8a285b8943baa491",
          "sha256": "a8ea702b428ed41efdcee637e2d12da4fa1c4822f38eda56452523f061c87253",
          "sha1": "cb696f9201e34afd5edecfd05d1307d77894008f",
          "md5": "d41b81ceb1d322160b73cc5bd7eca097"
        }
      ]
    }
  ]
}
