{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.11-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.11-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.11-1.20.jar",
          "size": 1351831,
          "sha512": "259b065602f57acdbb6e878c84f5f7ba7111c06d55c9193a52c8c3f8a6e207c017a7ea311aabf87598d809b362e90bee94e6bcde9bffc33b30e023625cf5cc76",
          "sha256": "b192760fb531c45468e4114bc4367e697e1c0b79fbcfaab599ed083416afbff0",
          "sha1": "c9586b782e896afb2742f8bfea61df1a872110bb",
          "md5": "01b0a4d85f07f510b382e0ccd1b95725"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.11-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.11-1.20.jar",
          "size": 1351831,
          "sha512": "259b065602f57acdbb6e878c84f5f7ba7111c06d55c9193a52c8c3f8a6e207c017a7ea311aabf87598d809b362e90bee94e6bcde9bffc33b30e023625cf5cc76",
          "sha256": "b192760fb531c45468e4114bc4367e697e1c0b79fbcfaab599ed083416afbff0",
          "sha1": "c9586b782e896afb2742f8bfea61df1a872110bb",
          "md5": "01b0a4d85f07f510b382e0ccd1b95725"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.11-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.11-1.20-sources.jar",
          "size": 146660,
          "sha512": "9afad090aca6eb6803665c9b67f23230e7fee979665ec6ae140270f4425030c5c8fbb3c4d6768ab30b60f2f59edd66dff7c1fc9b0d23360c4df1c6c03ee897ff",
          "sha256": "e42439b356bfea107afcbebd724b32eb045d86d1e2e4cb88b183a5582f995bb4",
          "sha1": "c6246c6a2c478a7c3272244886613a85fb077251",
          "md5": "dcdbafcb704b6de3c390c79992a56898"
        }
      ]
    }
  ]
}
