{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.4-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.4-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.4-1.20.jar",
          "size": 1351957,
          "sha512": "a694d073fb89da77d3f058ef5522227ea3fc7f743861d3e1179379f4095612fe98e70d7c40670a7fc94e279ccf6618304d0da18c56c7dde1e6aeebd0e57f37c2",
          "sha256": "485a725f91b394008585ce9f048e35683c1afaa7b177097318b84de0836b1872",
          "sha1": "9691cd0fd296cb8eb38be87b439bba3134a11b09",
          "md5": "1fb98261c7779e4c8e62170b46f5cbfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.4-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.4-1.20.jar",
          "size": 1351957,
          "sha512": "a694d073fb89da77d3f058ef5522227ea3fc7f743861d3e1179379f4095612fe98e70d7c40670a7fc94e279ccf6618304d0da18c56c7dde1e6aeebd0e57f37c2",
          "sha256": "485a725f91b394008585ce9f048e35683c1afaa7b177097318b84de0836b1872",
          "sha1": "9691cd0fd296cb8eb38be87b439bba3134a11b09",
          "md5": "1fb98261c7779e4c8e62170b46f5cbfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.4-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.4-1.20-sources.jar",
          "size": 146874,
          "sha512": "f7218fa45c1f6fff0b733e5d197106bf8a0cbe4cafeb344143c714b83b3f78696110c1ae8ea038a3bf43fad3cd1252bb4d307c0504557df3a40868526e65965c",
          "sha256": "a0be321ad69c4f16c6cd6a094621dc36a25c598944bf8c3ec3d288582b584e30",
          "sha1": "40af02e05c6b8082d0efa0a4213383326d2d2aab",
          "md5": "9ed062cfd573a25aa3652b337de35273"
        }
      ]
    }
  ]
}
