{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.26-1.20-pre4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.26-1.20-pre4.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.26-1.20-pre4.jar",
          "size": 1347605,
          "sha512": "90555c9c1a6e11453428df214d0044d632116415da209868f7a96aa381f4f63ee0644730724da270290f050428b0e3e91deadb96dc7c1e1ef55ac9eedd83aae5",
          "sha256": "d59746cf5e0481805ff65f297a17e186b264f8ae49867d38db31239b1dddceff",
          "sha1": "6843a85877b29d3f68242917180cca83efe227c8",
          "md5": "256c6ea9b09cc392984b3d8b242bde2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.2+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.26-1.20-pre4.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.26-1.20-pre4.jar",
          "size": 1347605,
          "sha512": "90555c9c1a6e11453428df214d0044d632116415da209868f7a96aa381f4f63ee0644730724da270290f050428b0e3e91deadb96dc7c1e1ef55ac9eedd83aae5",
          "sha256": "d59746cf5e0481805ff65f297a17e186b264f8ae49867d38db31239b1dddceff",
          "sha1": "6843a85877b29d3f68242917180cca83efe227c8",
          "md5": "256c6ea9b09cc392984b3d8b242bde2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.26-1.20-pre4-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.26-1.20-pre4-sources.jar",
          "size": 146696,
          "sha512": "463af44f7df80837ea15ea03484adaee593aa21f4b7ec3e4bc420949b337454211f886a440b888279b2742cae19b1d8960ec708dda2626320d39e7a43dc5852c",
          "sha256": "f86c227ae4b11558969127ad22e9dcf5b2bcaed08a1860ca2064feccc725e55b",
          "sha1": "a4abb021262fb04281d17bfb09ce5b75d4083c08",
          "md5": "b02b7b8b9e05c1172b3f73aa0af17371"
        }
      ]
    }
  ]
}
