{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.5-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.5-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.5-1.20.jar",
          "size": 1352619,
          "sha512": "b346c17ab778f9293a726528b0eb5a2e8f473d9942889e898abd545f22b82e6843268e9235f93806dae51da63eb9ccac37af1e5c9dd25803d25f1299412e6a70",
          "sha256": "3cb849e1e56027dcbf89c0718f57956d7cb3007a67f8794705af569e382cd48a",
          "sha1": "87c33783b41381893c877c66633bd29f6c7e895e",
          "md5": "b5fad6a73aa44d448724899cc2c02749"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.5-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.5-1.20.jar",
          "size": 1352619,
          "sha512": "b346c17ab778f9293a726528b0eb5a2e8f473d9942889e898abd545f22b82e6843268e9235f93806dae51da63eb9ccac37af1e5c9dd25803d25f1299412e6a70",
          "sha256": "3cb849e1e56027dcbf89c0718f57956d7cb3007a67f8794705af569e382cd48a",
          "sha1": "87c33783b41381893c877c66633bd29f6c7e895e",
          "md5": "b5fad6a73aa44d448724899cc2c02749"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.5-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.5-1.20-sources.jar",
          "size": 147339,
          "sha512": "e6db1713ba1b58ad62b372cb17e6cdea21fdf4559bd442840139c0c4b33b7814d491704daa3aa6345c18dd49cd414c4182832fcd665871dc97a5caf24e2202ac",
          "sha256": "c2a8fd2fb6791332f9fe8010898c6bdb3bc56a72d9e67e588c06e6981255f62f",
          "sha1": "d29b09f2253c689ac354cade041624de6cbddeeb",
          "md5": "4a7758913147ae8209c0a760a62410a2"
        }
      ]
    }
  ]
}
