{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.1.0-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.0-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.0-1.20.jar",
          "size": 1351604,
          "sha512": "5c1c8069015f338aa5fa6f5c4018f22d11b240746e0ae96015aa63aeac5df446f74b7e27a7de71d5726db37ea69abad205da3f4855c3de656c122c147ac7e70e",
          "sha256": "3946936a63d2656641cf1afb53b3fb70dcae7991f86abc012104ceaa76c0693a",
          "sha1": "90e8497b34366dac2bfdec08684b3569ef4bb3be",
          "md5": "c5ef21b0cd264a6c3a18e4a686194d5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.0-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.0-1.20.jar",
          "size": 1351604,
          "sha512": "5c1c8069015f338aa5fa6f5c4018f22d11b240746e0ae96015aa63aeac5df446f74b7e27a7de71d5726db37ea69abad205da3f4855c3de656c122c147ac7e70e",
          "sha256": "3946936a63d2656641cf1afb53b3fb70dcae7991f86abc012104ceaa76c0693a",
          "sha1": "90e8497b34366dac2bfdec08684b3569ef4bb3be",
          "md5": "c5ef21b0cd264a6c3a18e4a686194d5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.1.0-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.1.0-1.20-sources.jar",
          "size": 146703,
          "sha512": "9aaf33cf494a9c0f9514368985d643c22e4f5de242bec12dbcd1b5fd43279001ffac7a78031d70f699d529415fcd2418602b0025ab8d4a9b2bfc549b6720270f",
          "sha256": "93c6d42d7410ea1d014a0debe83e12d2739e0ad4ba436b3ce6b44b230d797441",
          "sha1": "7b8a10fcd916da48615d35a9904da191f60abea5",
          "md5": "4057775960407744f35067dbe82fd074"
        }
      ]
    }
  ]
}
