{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.21-23w16a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.21-23w16a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.21-23w16a.jar",
          "size": 1050135,
          "sha512": "2a94246f6027da6a9c95e3a75b508259e78d9bce5c322188c64cf084d67fac56b2badc3e97d7886a999ded519c103cce12d423f7d2eabcdaef7746e3430d8e73",
          "sha256": "04c568c85c8c28c1125b3903d0813f74536b062cdafad536915d24c89c03c5b2",
          "sha1": "ce3878b54e646dea01e0b326ad58af5e25d39b55",
          "md5": "48315273ac68b86433d8ad4c0f4634df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.79.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.21-23w16a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.21-23w16a.jar",
          "size": 1050135,
          "sha512": "2a94246f6027da6a9c95e3a75b508259e78d9bce5c322188c64cf084d67fac56b2badc3e97d7886a999ded519c103cce12d423f7d2eabcdaef7746e3430d8e73",
          "sha256": "04c568c85c8c28c1125b3903d0813f74536b062cdafad536915d24c89c03c5b2",
          "sha1": "ce3878b54e646dea01e0b326ad58af5e25d39b55",
          "md5": "48315273ac68b86433d8ad4c0f4634df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.21-23w16a-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.21-23w16a-sources.jar",
          "size": 145802,
          "sha512": "ad15f11aa9b41cd6100fd4ff176374ca4f1cefbae6dd94925aac7c7b5ab2ac8ca0ce195ca49bf342c9cb030a7d3541172aee46af1d8a693ef942862495fbe94c",
          "sha256": "73805fb3d475e8e60502d993e437989973fe642f5ec3b14669870aedcc32fcef",
          "sha1": "4f70279da3fe39f6946b1bab5efc296b52274993",
          "md5": "32348e1879ebfc81b472524086a19477"
        }
      ]
    }
  ]
}
