{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.42-1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.42-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.42-1.20.jar",
          "size": 1361614,
          "sha512": "7aaab42102d793d29e25aad2ececbdd2b5f08747411feb103f1ead867e3b5902fe7476714b1214290171ce29310cb122227df84bdc72a8f4f554101b195f0a3d",
          "sha256": "752c27e3c858336e487fc6fd28175418db6cb578717ac284b4b79f4891ba5354",
          "sha1": "9b40ef8e6844f3450014eccd53f63c439aef2581",
          "md5": "b3ac0ee9608a46fae985399c6eac8458"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.42-1.20.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.42-1.20.jar",
          "size": 1361614,
          "sha512": "7aaab42102d793d29e25aad2ececbdd2b5f08747411feb103f1ead867e3b5902fe7476714b1214290171ce29310cb122227df84bdc72a8f4f554101b195f0a3d",
          "sha256": "752c27e3c858336e487fc6fd28175418db6cb578717ac284b4b79f4891ba5354",
          "sha1": "9b40ef8e6844f3450014eccd53f63c439aef2581",
          "md5": "b3ac0ee9608a46fae985399c6eac8458"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.42-1.20-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.42-1.20-sources.jar",
          "size": 152499,
          "sha512": "866e735a204172d0d161ae0db5198614653b2340612acd33acd721151e0d78a4bb9b233d43fc3f9e7efefb6a01b6a221ee1d2f4fd1680489d00b8c5dca020781",
          "sha256": "447b24e537e059672a27af5c14d0d487c3ef73c7185c4496b50e2b44391b9ddf",
          "sha1": "f29af7ce79955dafb52ecaa2665d3ab084d05143",
          "md5": "cd51838d6973fc1996081b35d0452786"
        }
      ]
    }
  ]
}
